language: node_js
node_js:
- '8'
notifications:
  email: false
deploy:
  provider: npm
  email: davidstoreypickart@gmail.com
  api_key:
    secure: Q8XLHP7V82osaj9Ii0s5REDjJGhRAFT1/daNskSyD/LqvH9sI86Zhi/7HN+2fri0zDcbbkA+lb8jrcWPq7u9g4aDlK8hGKs2jw2zgb/DXhS4c5bRwjXV6x+7Xd6z4z37lsqwUjoTEzI9FaD1awAj0yb75NLKtkuJpdG5DwnC9XtO4C7NguV+aP1LCiIOW6vmSANFrNOxmwuq2lx0Z5D8DJjj64iBWuHxL3XoISRChR8ZMfYgnrCJaKqEhkt/cpQZjyv+ycnat+UrAuZ3Z6TLatnVTrT3ABgwHskLL214fqkO+Bge+lyRUNgMBci35YEJGv8Q5ZmP+l9zISnCXsJNyM50x6N9PxYX3YdkHEK0paMHOGe8ee0slifDHOZFVcEuDE1/JHNmYsvWmnPpGENmIUJ8VoJqgWPXabZdvxCZzcTBQpih+PeX7ojZAWYigAOUJElN+lwefaeHrbk+uHE8ru/ILrwr9rVaRkZXqsyduOiokI/JRvzw5P4c4ATzyQhOPBzW5sGtVQHhCGBSgpnT3noVlnnjghz0zrxBk/aUH6c3JPF8Q5wZ+kkzZevoDTtoHmk89GQBbSFHmrwZ+UUyh7BR/gC5woOPYpNQ7Y3l/zooQSUAcGpcl0X/v+HU+O0/nw1gT8mZ53ATzzthYGvP8UwPhQOZVthsXfnwiVGSylc=
  on:
    branch: master
  skip_cleanup: true
